//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockLikeNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int IdArticle { get; set; }
        public string ArticleText { get; set; }
        public int LikeCount { get; set; }
    }
}
