//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockLikeNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public int ID_ARTICLE { get; set; }
        public string ARTICLE1 { get; set; }
        public int LIKE_COUNT { get; set; }
    }
}
